name: Particles build tests

on:
  push:
    branches-ignore: 'main'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
  pull_request:
  workflow_dispatch:

jobs:
  linuxXlinux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential xorg-dev mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev libxinerama-dev libxcursor-dev xvfb x11-apps vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools

    - name: linux-linux
      run: ./build.sh -t -r -e

  linuxXwindows:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y xorg-dev build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix libxinerama-dev libxcursor-dev vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools

    - name: linux-X-windows
      run: ./build.sh -t -w -r -e

  macOS:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install cmake gcc git wget python
          wget https://vulkan.lunarg.com/sdk/download/1.2.189.0/mac/vulkansdk-macos-1.2.189.0.dmg
          hdiutil attach vulkansdk-macos-1.2.189.0.dmg
          cd /Volumes/vulkansdk-macos-1.2.189.0/
          sudo ./InstallVulkan.app/Contents/macOS/InstallVulkan --root ~/ --accept-licenses --default-answer --confirm-command install
          ls ~/
          cd ~/VulkanSDK/1.2.189.0
          python install_vulkan.py

    - name: macos-macos
      run: ./build.sh -o -e -r
