name: Documentation
on: 
  push:
      branches: [ "main" ]
      paths-ignore:
        - 'docs/**'
        - '.github/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: checkout
      run: |
        git config --global user.name 'BurrowBot'
        git config --global user.email 'BurrowBot@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.BURROW_BOT }}@github.com/$GITHUB_REPOSITORY
        git checkout --track origin/doc
        git rebase main

    - name: build
      run: doxygen docs/doxygen.config
    
    - name: push
      run: |
        git config --global user.name 'BurrowBot'
        git config --global user.email 'BurrowBot@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.BURROW_BOT }}@github.com/$GITHUB_REPOSITORY
        git add docs/
        git commit -m "docs automatic update"
        git push origin doc
